# Change these first
owner: Inbox-Design # Your GitHub organization or username, where this repository lives
repo: bridge-status # The name of this repository

sites:
  - name: School Bridge App
    url: https://tidewater.bridge.school.nz
  - name: API 1
    url: https://api-191.bridge.school.nz
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name: API 2
    url: https://api-193.bridge.school.nz
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name: Login
    url: https://login.bridge.school.nz

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.bridge.school.nz
  # baseUrl: /your-repo-name
  logoUrl: https://inboxdesign.ibcdn.nz/logo_schoolbridge.svg
  name: SchoolBridge
  introTitle: "School solutions to save you time, and help your Whānau"
  introMessage: A Collection of Tools that Seamlessly Connects Schools, Caregivers & Students [**Learn More**](https://www.inboxdesign.co.nz/)
  navbar:
    - title: Status
      href: /
    - title: Inbox Design
      href: https://www.inboxdesign.co.nz/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
